### PR TITLE
Deep sort hashes

### PR DESCRIPTION
**Pull request by tomas321**
Added new dependency 'deepsort' gem from 'https://github.com/mcrossen/deepsort'.
This PR is a prerequisite for #50. If it's merged, I will rebase #50 to master and make the necessary changes.

### CODE REVIEW

**Comment by Teebor-Choka** [comment]
The code looks good. Any ETA on this being merged? This functionality is needed for multiple other PRs.

**Comment by ypid-geberit** [comment]
Hi @tomas321, like your other PR #50, this one also looks like a duplicate. There is already ongoing discussion about this in #41.

**Comment by tomas321** [comment]
Hi @ypid-geberit, sorry for for the confusion. I needed this feature with combination of #50 and this change and even though #41 fixes the deep sort problem, I tried to be the least invasive to the current code. Although your solution is independent of external libraries, which is better in the long term, it presents possible duplicate to the tested and existent library [mcrossen/deepsort](https://github.com/mcrossen/deepsort).

To compare, both solutions deepsorts the event objects, #41 still proposes breaking changes with  the `serialize` function, #52 has no breaking changes and backward compatibility is ensured as in #41 with the `deep_sort` variable defaulting to False.

**Comment by ypid-geberit** [comment]
Thanks very much! I guess when external dependencies, are ok, your solution is cleaner, has no breaking changes by default (which was also my intention with #41, which was still waiting on further info) and should thus preferred.

**Comment by kares** [comment]
Thanks for the PR, I've looked into *deepsort* gem and I am not sure I like bringing it in as a dependency.
First of its monkey-patching core and has way more functionality than we need here (one `deep_sort` method).
Even if that concern is negligible there's "weird" stuff such as the [re-defined map ordering](https://github.com/mcrossen/deepsort/blob/master/lib/deepsort.rb#L97). 
This does not seem very fortunate, I think the plugin should have an explicit path on what we're doing for non-comparables.

So before doing a review here it would be worth re-thinking the "deep-sort" method in house.

**Comment by ypid-geberit** [comment]
Nice to see this bug finally got fixed by #55. This alternative PR can probably be closed.

**Comment by roaksoax** [comment]
Closing this PR as per the above comment.

**Pull request closed without merging**
