### PR TITLE
Doc: Clarify behavior for concatenate_sources option

### PR DESCRIPTION
**Pull request by karenzone**
Related: #59

### CODE REVIEW

**Comment by karenzone** [comment]
@kaisecheng Here's a first draft. I look forward to discussing with you and refining the content.

**Comment by karenzone** [comment]
@kaisecheng  Will you please take a quick look to be sure that I interpreted your review comments correctly?  The info and examples you provided were very helpful, and I gave you an authoring credit. :-)

**Comment by kaisecheng** [comment]
@karenzone  the examples look good 💯 thanks for the credit ❤️

**Comment by karenzone** [comment]
Published at v3.2.3: https://rubygems.org/gems/logstash-filter-fingerprint/versions/3.2.3

**Pull request merged**
